
const supabaseUrl = 'https://bljkmdfhykdwrnzrrshc.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsamttZGZoeWtkd3JuenJyc2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTc0OTMsImV4cCI6MjA1OTk5MzQ5M30.nH3Lq8KPNLw5XT2_2GCvlSqlPJGVDxx_aldPyRHdtOA';
const supabase = supabase.createClient(supabaseUrl, supabaseKey);
